// This file is automatically generated. Do not modify it manually.
// Code generated .* DO NOT EDIT.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "jenkins",
	Version: "1.1.0",
}
